name: Deploy

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  deplay-staging:
    name: GAE deplay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # わけてアップするとリージョン違いを懸念した警告がでるので合わせ、cronにtimezoneを追加
          deliverables: app.yaml, cron.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v3
          promote: true
