name: Deploy

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  deplay-staging:
    name: GAE deplay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
          version: v2
          promote: false

      - name: Deploy an App Engine cron
        id: deploy-cron
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: cron.yaml
          version: v2
          promote: true
