name: Deploy

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  deplay-staging:
    name: GAE deplay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v2
          promote: true

      - name: Deploy an App Engine cron
        id: deploy-cron
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: cron.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v2
          promote: true
