name: Deploy&Released NEW version.

on: [ push ]

jobs:
  deplay-staging:
    name: GAE deplay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authentication setting for Deploy
        id: deploy-auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          # version: v1  # 切り戻し対応、コメントアウトでバージョン名がデフォルト(日付時間)
          promote: false

      - name: Deploy an App Engine cron
        id: deploy-cron
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: cron.yaml
          # version: v1   # gae cron deploy にバージョン切り替え不可

      - uses: google-github-actions/setup-gcloud@v0

      - name: Remove older versions except the latest 3 waiting versions
        run: gcloud app versions list | grep 20......t.........0.00 | sort -r | awk '3 < NR{print $2}' | xargs gcloud app versions delete

      - name: Publish of latest date version
        if: true   # false:手動公開, true:即時公開したい場合は 　　# この切り替えスイッチ取得は都合に合わせて変更ください。
        run: gcloud app versions list | grep 20......t......... | sort -r | awk 'NR==1{print $2}' | xargs gcloud app versions migrate
