name: GAE versions tools.

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'ツールを選択してください。'
        required: true
        type: choice
        options:
        - test
        - other

jobs:

  job-test:
    if: github.event.inputs.tags == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - name: テストコマンドの実行
        run: |
          gcloud info
          echo "TEST"


