name: GAE versions tools.

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'ツールを選択してください。'
        required: true
        type: choice
        options:
        - test
        - clean

jobs:

  job-test:
    if: github.event.inputs.tags == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - name: テストコマンドの実行
        run: |
          gcloud info
          echo "TEST"

  job-clean:
    if: github.event.inputs.tags == 'clean'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - name: テストコマンドの実行
        run: |
          echo 'GAEの待機バージョンを最新３つ残しそれ以外を削除します'
          gcloud app versions list | grep 20......t.........0.00 | sort -r | awk '3 < NR{print $2}' | xargs gcloud app versions delete

