name: GAE versions tools.

on: [ workflow_dispatch ]

jobs:

  job-test:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize gcloud
        uses: actions/checkout@v3
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - run: 'gcloud info'
      - run: echo "TEST"


