name: GAE versions tools.

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'ツールを選択してください。'
        required: true
        type: choice
        options:
        - show
        - clean
        - server-stop
        - server-start
        - server-switchback

jobs:

  job-show:
    if: github.event.inputs.tags == 'show'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: |
          echo 'GAEで稼働中のバージョンを表示します'
          gcloud app versions list | grep ' 1.00 ' | sort -r | awk 'NR==1{print $2}' | xargs echo
  
  job-clean:
    if: github.event.inputs.tags == 'clean'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: |
          echo 'GAEの日付バージョン(待機中)を最新３つ残しそれ以外を削除します'
          gcloud app versions list | grep 20......t.........0.00 | sort -r | awk '3 < NR{print $2}' | xargs gcloud app versions delete

  job-stop:
    if: github.event.inputs.tags == 'server-stop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: |
          echo 'GAE内のstop503errorバージョンを公開します'
          gcloud app versions migrate stopped-503error

  job-start:
    if: github.event.inputs.tags == 'server-start'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: |
          echo 'GAE内の日付バージョン最新を公開します'
          gcloud app versions list | grep 20......t......... | sort -r | awk 'NR==1{print $2}' | xargs gcloud app versions migrate

  job-switchback:
    if: github.event.inputs.tags == 'server-switchback'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: |
          echo 'GAE内の日付バージョン切り戻し版を公開します'
          gcloud app versions list | grep 20......t......... | sort -r | awk 'NR==2{print $2}' | xargs gcloud app versions migrate

